eureka:
  cliente:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      mvc:
        routes:
        - id: users
          uri: http://localhost:9090
          predicates: 
          - Path=/api/users/**
        - id: comments
          uri: http://localhost:8090
          predicates:
          - Path=/api/posts/*/comments/**
        - id: posts
          uri: http://localhost:8050
          predicates:
          - Path=/api/posts/**